### ISSUE TITLE
MessageQueue : How it works ?

### ISSUE THREAD

**Issue by Fabrice70** [mhdawson/PI433WirelessRecvManager#1]
Hello,
It is a really nice project that you did here and I would like to partially implement it (not with all the sensors). I am currently trying to understand the Message Queue linked list concept - I am curious and not a high skill developer ! -
However, although the enqueue function is quite clear I have more questions regarding the dequeue function. After the dequeue function is called in the PI433.cpp, the newMessages pointer - part of MessageQueue class - is set to NULL which I understand means that all previous messages stored in the messages tab are ignored if a second dequeue function call is made. I am sure I do not interpret correctly here.
Could you just clarify ?
Thank you.
I know its quite a long time ago that you posted this project !
Fabrice70

**Comment by mhdawson** [comment]
The method is : MessageQueue::dequeueMessages(void) , with the key to your question being that s on the end of dequeueMessages.  It dequeues all of the messages at one time! That's why the newMessage pointer is set to NULL.

The code that calls dequeueMessages then makes sure to process all of the messages that were returned:

```C++
    Message* currentMessages = queue->dequeueMessages(); 
      if (NULL != currentMessages) { 
         Message* nextMessage = currentMessages;
         Message* lastMessage = NULL;
         while(NULL != nextMessage) {
```

**Comment by Fabrice70** [comment]
Thank you. That's smart.
